### ISSUE TITLE
Need to replace regular expressions with FSMs

### ISSUE THREAD

**Issue by santi224m** [Fanaticaj/CPSC-323-Compiler#7]
I found this in the assignment 1 document.

>You can build your entire lexer using a FSM, Or build using at least FSMs for identifier,
>integer and real (the rest can be written ad-hoc) but YOU HAVE TO CONSTRUCT A FSM
>for this assignment otherwise, there will be a deduction of 2 points!

It looks like we need to use finite-state machines to identify the token types in the lexer.

**Comment by santi224m** [comment]
I created a FSM to check for real numbers. Now we just need one for identifiers and one for integers.
I also uploaded my [design](https://github.com/Fanaticaj/CPSC-323-Compiler/blob/master/FSM_design/real_fsm.pdf) in case we need it for documentation.

**Comment by Fanaticaj** [comment]
Ahhh shooot. Really thought RE's would be a nice clean way to accomplish this. Thanks for pointing it out.
